# Generated by Django 5.1.2 on 2024-10-18 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_allergy_preference_recipe_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.allergy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.preference'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_notification_hour',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_recipes',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='api.recipe'),
        ),
    ]
